variables:

stages:
 - train
 - test
 - image
 - deploy

api-tests:
  stage: test
  allow_failure: false
  script:
    - pytest text.py

model-training:
  stage: train
  allow_failure: false
  script:
    - make the pkl file
    - ensure pkl was created or fail

deploy-model:
  stage: deploy
  script:
    - tf plan
    - tf deploy